import './globals.css'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import { Footer, Header } from '@/components'

const roboto = Roboto({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className={`${roboto.className} min-h-screen px-10 md:px-24`}>
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
