export const siteMetadata = {
  title: 'Site Pessoa - Zoranildo Santos',
  author: 'Zoranildo Santos',
  headerTitle: 'Site Pessoa',
  description: 'Site pessoal do engenheiro de software Zoranildo Santos, com artigos sobre desenvolvimento web, meu currículo e informações sobre mim.',
  language: 'pt-br',
  theme: 'system',
  siteUrl: 'https://zorasantos.dev',
  siteLogo: '/src/assets/logo.png',
  socialBanner: '/src/assets/logo.png',
  email: 'fzorasantos@gmail.com',
  github: 'https://github.com/ZoraSantos',
  youtube: 'https://www.youtube.com/@MrZoranildo',
  linkedin: 'https://www.linkedin.com/in/zoranildosantos',
  locale: 'pt-BR',
}